export default{
    masters:[
        {
          key: '0',
          data: 'product_master',
          label: 'Product Master',
          children: [
            { key: '0-0', data: 'item_no', label: 'Item no.' },
            { key: '0-1', data: 'item_name', label: 'Item name' },
            { key: '0-2', data: 'additions_details', label: 'Additional Details' },
            { key: '0-3', data: 'category', label: 'Category' },
            { key: '0-4', data: 'brand', label: 'Brand' },
            { key: '0-5', data: 'container_type', label: 'Container Type' },
            { key: '0-6', data: 'pack', label: 'Pack' },
            { key: '0-7', data: 'pack_size', label: 'Pack Size' },
            { key: '0-8', data: 'uom', label: 'UOM' },
            { key: '0-9', data: 'cbm', label: 'CBM' },
            { key: '0-10', data: 'loading_per_container', label: 'Loading per container' },
            { key: '0-11', data: 'origin', label: 'origin' },
            { key: '0-12', data: 'loading_port', label: 'Loading Port' },
            { key: '0-13', data: 'last_fob', label: 'Last FOB' },
            { key: '0-14', data: 'currency', label: 'Currency' },
            { key: '0-15', data: 'date', label: 'Date' },
            { key: '0-16', data: 'supplier', label: 'Supplier' },
            { key: '0-17', data: 'supplier_ref_no', label: 'Supplier ref no.' },
            { key: '0-18', data: 'pcs', label: 'PCS' },
            { key: '0-19', data: 'ctn', label: 'CTN' }
          ]
        },
        {
          key: '1',
          data: 'customer_master',
          label: 'Customer Master',
          children: [
            { key: '1-0', data: 's_no', label: 'S no.' },
            { key: '1-1', data: 'group_name', label: 'Group name' },
            { key: '1-2', data: 'buyer_name', label: 'Buyer Name' },
            { key: '1-3', data: 'address', label: 'Address' },
            { key: '1-4', data: 'country', label: 'Country' },
            { key: '1-5', data: 'contact_person', label: 'Contact Person' },
            { key: '1-6', data: 'email', label: 'Email' },
            { key: '1-7', data: 'contact_no', label: 'Contact no.' }
          ]
        },
        {
          key: '2',
          data: 'supplier_master',
          label: 'Supplier Master',
          children: [
            { key: '2-0', data: 's_no', label: 'S no.' },
            { key: '2-1', data: 'supplier_name', label: 'Supplier name' },
            { key: '2-2', data: 'phone_no', label: 'Phone no' },
            { key: '2-3', data: 'address', label: 'Address' },
            { key: '2-4', data: 'pincode', label: 'Pincode' },
            { key: '2-5', data: 'bank_name', label: 'Bank name' },
            { key: '2-6', data: 'bank_address', label: 'Bank address' },
            { key: '2-7', data: 'bank_account_no', label: 'Bank account no' },
            { key: '2-8', data: 'iban_no', label: 'IBAN no' },
            { key: '2-9', data: 'swift_code', label: 'Swift code' },
            { key: '2-10', data: 'country', label: 'Country' },
            { key: '2-11', data: 'payment_term', label: 'Payment Term' },
            { key: '2-12', data: 'contact_person', label: 'Contact Person' },
            { key: '2-13', data: 'email', label: 'Email' },
            { key: '2-14', data: 'contact_no', label: 'Contact no' }
          ]
        },
        {
          key: '3',
          data: 'shipment_master',
          label: 'Shipment Master',
          children: [
            { key: '3-0', data: 'po_no', label: 'PO no.' },
            { key: '3-1', data: 'supplier', label: 'Supplier' },
            { key: '3-2', data: 'country', label: 'Country' },
            { key: '3-4', data: 'buyer', label: 'Buyer' },
            { key: '3-5', data: 'customer', label: 'Customer' },
            { key: '3-6', data: 'supp_po_date', label: 'Supp PO Date' },
            { key: '3-7', data: 'invoicing_party', label: 'Invoicing Party' },
            { key: '3-8', data: 'our_po_date', label: 'Our PO Date' },
            { key: '3-9', data: 'our_po_no', label: 'Our PO no' },
            { key: '3-10', data: 'payment_term', label: 'Payment Terms' },
            { key: '3-11', data: 'supp_po_value', label: 'Supp PO Value' },
            { key: '3-12', data: 'sup_po_no', label: 'Supp PO no' },
            { key: '3-13', data: 'currency', label: 'Currency' },
            { key: '3-14', data: 'loading_port', label: 'Loading Port' },
            { key: '3-15', data: 'destination_port', label: 'Destination Port' },
            { key: '3-16', data: 'final_destination', label: 'Final Destination' },
            { key: '3-17', data: 'inspection', label: 'Inspection' },
            { key: '3-18', data: 'cust_po_no', label: 'Cust PO no' },
            { key: '3-19', data: 'number_of_container', label: 'Number of Container' },
            { key: '3-20', data: 'adv_rec_date', label: 'Adv Rec Date' },
            { key: '3-21', data: 'adv_pay_date', label: 'Adv Pay Date' },
            { key: '3-22', data: 'purchase_invoice', label: 'Purchase Invoice' },
            { key: '3-23', data: 'sale_invoice_val', label: 'Sale Invoice Val' },
            { key: '3-24', data: 'sale_inv_no', label: 'Sale Inv no' },
            { key: '3-25', data: 's_f_inv_no', label: 'Supplier Final Invoice no' },
            { key: '3-26', data: 's_final_inv_value', label: 'Supplier final invoice value' },
            { key: '3-27', data: 'final_rec_date', label: 'Final Rec Date' },
            { key: '3-28', data: 'final_pay_date', label: 'Final Pay Date' },
            { key: '3-29', data: 'percentage', label: 'Percentage' },
            { key: '3-30', data: 'commission', label: 'Commission' },
            { key: '3-31', data: 'share', label: 'Share' },
            { key: '3-32', data: 'payment_request_lot', label: 'Payment Request Lot' },
            { key: '3-33', data: 'dhl_no', label: 'DHL no' },
            { key: '3-34', data: 'cod_number', label: 'COD Number' },
            { key: '3-35', data: 'rfi_date', label: 'RFI Date' },
            { key: '3-36', data: 'consignee', label: 'Consignee' },
            { key: '3-37', data: 'freight_booking_date', label: 'Freight Booking Date' },
            { key: '3-38', data: 'freight_booking_no', label: 'Freight Booking no' },
            { key: '3-39', data: 'shipping_line', label: 'Shipping Line' },
            { key: '3-40', data: 'incoterm', label: 'Incoterm' },
            { key: '3-41', data: 'mode_of_transport', label: 'Mode of Transport' },
            { key: '3-42', data: 'estimated_dob', label: 'Estimated DOB' },
            { key: '3-43', data: 'revised_dob', label: 'Revised DOB' },
            { key: '3-44', data: 'actual_dob', label: 'Actual DOB' },
            { key: '3-45', data: 'scan_bl_date', label: 'Scan BL Date' },
            { key: '3-46', data: 'stuf_photo', label: 'Stuf Photo' },
            { key: '3-47', data: 'est_arriv_date', label: 'Est Arriv Date' },
            { key: '3-48', data: 'bl_no', label: 'BL no' },
            { key: '3-49', data: 'remarks', label: 'Remarks' },
            { key: '3-50', data: 'draft_cnca', label: 'Draft CNCA' },
            { key: '3-51', data: 'original_cnca', label: 'Original CNCA' },
            { key: '3-52', data: 'cnca_agent', label: 'CNCA Agent' },
            { key: '3-53', data: 'dup', label: 'DUP' },
            { key: '3-54', data: 'po_details_item', label: 'PO Details(item name)' },
            { key: '3-55', data: 'po_details_qty', label: 'PO Details(Qty)' },
            { key: '3-56', data: 'po_details_price', label: 'PO Details(Price)' },
            { key: '3-57', data: 'container_details_container_no', label: 'Container Details(Container no)' },
            { key: '3-58', data: 'container_details_item', label: 'Container Details(item name)' },
            { key: '3-59', data: 'container_details_container_type', label: 'Container Details(Container type)' },
            { key: '3-60', data: 'container_details_qty', label: 'Container Details(Qty)' },
          ]
        }
      ]
}